### ISSUE TITLE
MacOS build

### ISSUE THREAD

**Issue by atortsev** [Unisay/purescript-lua#14]
Any plans for MacOS build? Especially for M1 lineage. Really want to use this with defold game engine.

**Comment by Unisay** [comment]
The reason I didn't enable the MacOS build in the nix configuration is simply that I don't have a mac to try building it on. 
I suggest you to try building `pslua` executable outside of the nix context; You'd need to have cabal/ghc installed in your system and available on $PATH. A good conventional way to do it is [GHCUp](https://www.haskell.org/ghcup/). It might simply work then. Here is the similar solution but for windows build: https://github.com/Unisay/purescript-lua/issues/13#issuecomment-1722525359

**Comment by Unisay** [comment]
If you decide to go this route and encounter problems please let me know, I'll try to help.

**Comment by atortsev** [comment]
I'll try. Thank you!

**Comment by unorsk** [comment]
> Any plans for MacOS build? Especially for M1 lineage. Really want to use this with defold game engine.

It's actually easy to get pslua compiled locally :) I've just ran `cabal install exe:pslua` using ghc-9.4.7 and it worked like a charm!

**Comment by atortsev** [comment]
Yeah, it's worked! Thank you!
