### ISSUE TITLE
Please add support for `Data.Lazy` to the package-set

### ISSUE THREAD

**Issue by tomshackell** [Unisay/purescript-lua#18]
This commonly used library uses a tiny bit of javascript but appears to be missing from the package-set:
```
Foreign file for the module ".spago\\lazy\\v6.0.0\\src\\Data\\Lazy.purs" not found in the following locations:
-  C:\Dev\pslua-test\purs\.spago\lazy\v6.0.0\src\Data\Lazy.lua
-  C:\Dev\pslua-test\purs\.spago\lazy\v6.0.0\src\Data\Lazy.lua
```
Here is the javascript required:
```
export const defer = function (thunk) {
  var v = null;
  return function() {
    if (thunk === undefined) return v;

    v = thunk();
    thunk = undefined; // eslint-disable-line no-param-reassign
    return v;
  };
};

export const force = function (l) {
  return l();
};
```
A lua equivalent would be something like:
```
return {
    defer = (function (thunk)
        local v = nil
        return function ()
            if thunk == nil then return v end
            v = thunk()
            thunk = nil
            return v
        end
    end),
    force = (function (l) return l() end),
}
```

**Comment by Unisay** [comment]
I [have forked](https://github.com/Unisay/purescript-lua-lazy) the `lazy` library and will work on adding to the package set asap. This library depends on [a few other libs](https://github.com/Unisay/purescript-lua-lazy/blob/5164b9c3aaa5904dd5b5f829adb903e7abc0bc7c/bower.json#L22) that aren't added (and those might depend on others...) so it might take a bit of time. Stay tuned!

**Comment by tomshackell** [comment]
I got it temporarily working (hacking my local `.spago`) by adding just the `Lazy.lua` I included above.

**Comment by Unisay** [comment]
Nice! It turned out to be easy
```
 * [new tag]         psc-0.15.15-20240417 -> psc-0.15.15-20240417
```
you can upgrade the package set, the `lazy` lib has been added!

**Comment by Unisay** [comment]
Please report if it works for you, I'll close the issue then.

**Comment by tomshackell** [comment]
Yup that works, thanks :-)
