### ISSUE TITLE
Incorrect arguments when using flip

### ISSUE THREAD

**Issue by sarahnya** [Unisay/purescript-lua#22]
This
```purescript
module Main where

import Prelude
import Effect (Effect)
import Effect.Console (log)

main ∷ Effect Unit
main = log $ flip (<>) "b" "a"
```
results in this generated lua
```lua
return (function(s) return function() print(s) end end)((function(s1) return function(s2) return s1 .. s2 end end)(a)("a"))()
```

It has an undefined variable `a`, is missing `"b"`, and `"a"` is being passed as the wrong argument.

**Comment by sarahnya** [comment]
I did a little more investigating and the name of the undefined variable in the lua output comes from then name of the parameter in `flip`.

So replacing `flip` with `(\f foo bar -> f bar foo)` in my example generates
```lua
return (function(s) return function() print(s) end end)((function(s1) return function(s2) return s1 .. s2 end end)(bar)("a"))()
```

**Comment by Unisay** [comment]
Thank for reporting, that's a good catch. I'll fix it asap.

**Comment by Unisay** [comment]
Please let me know if this fixed it for you, or simply close this issue if it did.

**Comment by sarahnya** [comment]
Fixed ty!~ :D
