### ISSUE TITLE
Arrays of type `Array Unit` are always empty

### ISSUE THREAD

**Issue by sarahnya** [Unisay/purescript-lua#23]
Since `unit` is being represented as `nil` in the generated lua, all arrays of type `Array Unit` are treated as empty.

minimal example:
```purescript
module Main where

import Prelude
import Effect (Effect)
import Effect.Console (logShow)
import Data.Array (length)

main :: Effect Unit
main = logShow $ length [unit, unit, unit]
```
generates
```lua
local M = {}
M.Data_Unit_foreign = { unit = nil }
return (function(s) return function() print(s) end end)((function(n) return tostring(n) end)((function(xs) return #xs end)({
  [1] = M.Data_Unit_foreign.unit,
  [2] = M.Data_Unit_foreign.unit,
  [3] = M.Data_Unit_foreign.unit
})))()
```
and outputs 0 when run.

Any expression that uses the array implementation of `guard` will be affected by this.

**Comment by sarahnya** [comment]
https://www.lua.org/manual/5.1/manual.html#2.5.5

**Comment by sarahnya** [comment]
I think `unit` being represented with `nil` will also cause `Record.Unsafe.unsafeHas` to return `false` for fields with type `Unit`.

**Comment by Unisay** [comment]
This is a good find too! 

Thanks for reporting, 
I will be looking at fixing this bug later today.

**Comment by Unisay** [comment]
Should be fixed now: I've changed the representation of `Data.Unit` from `nil` to `{}`, make sure you use the latest package set with "prelude" v7.2.0.

**Comment by sarahnya** [comment]
That fixed it ty!~ I did find another unrelated issue again while testing that this one is fixed but I'll open another issue for that in just a bit.
