### ISSUE TITLE
Very nice project

### ISSUE THREAD

**Issue by i-am-the-slime** [Unisay/purescript-lua#25]
Hey Yura,

very cool that you're doing this.
Have you tried it yet with something like Löve2D, the engine?

Or would you say that's a bad idea?

**Comment by i-am-the-slime** [comment]
Posted this in ideas.

**Comment by Unisay** [comment]
> Hey Yura,

Hi Mark! 

> very cool that you're doing this.
Thanks

> Have you tried it yet with something like Löve2D, the engine?
No, I haven't tried it. I would love to support those who want to try any game engines the best I can. 

I did try writing a neovim plugin though. It does work, but somebody needs to cover neovim API with FFI bindings once.

> Or would you say that's a bad idea?
Not at all, this is a good one.
